---
#
# Ansible managed
#
language: python

os: linux
dist: xenial

python:
  - "3.9"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  jobs:
    - image="alpine" tag="latest"
    - image="centos" tag="7"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="32"
    - image="fedora" tag="latest"
    - image="fedora" tag="rawhide"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"
    - image="ubuntu" tag="xenial"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - function retry { counter=0 ; until "$@" ; do exit=$? ; counter=$(($counter + 1)) ; if [ $counter -ge 3 ] ; then return $exit ; fi ; done ; return 0; } ; retry tox

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "r3jVLnm/R2SpbBC/eUdEUIYa4PtgHTDGYElHIITQk2vJpKrJQN2VaJNPDhdKi82AsjAdRc8UJ8hg0sPCDpq+YMXo+KpteRG8iUWcp4powtneM4dqugd2yIrTauuareq1CZ2Ea+e7zYs+kIhIQhjYkgRZAccV9kwtkmwOSfrEyOcU1951i4jXDFiBu097VUnEwpkEVs3mqjm+e6U6wKORy1+UBa7dEFAIM69fWWtnjANcXZbG5a2eU0EBSAEhg4igqsru+ARgKTGgGls8kBn8R74wPfllgsyJpKTt+iHxHj7NYK9SKFHh7ZqZOoQSXtUsrJcHh8noNXt7CzwZB2JwQdZrRZIZVV0YKwc6Br55+pTOzw+o06ZMsFqKZWCRcj39taEd3lHyMNFLGJrUiXaQQ/VGG0cGnV28YthV+y7JMiPsLMdlRbe2Plg0VpsylzwSMwO6gPEqaiihe3um3MUXizQpfcY9CqXqNFJSPKRLbs3lgbloSy6FSjb2DL8poTX1VIOuw58GOP4sNo2FN50Ykv484O/RpLDfy+BEMjwUQqETAhnXANgcBvUXqcyzF51oGUPbDLgisxkezkq+mPR/gUmI0DSOrC520L2rPpy/b2zzkSBqN+4yKX9DNVZJhbPmvP2rvub5PfduiheafqwCc8Spw9ioSKxgzcEPkMfOryA="
    on_success: change
    template: "%{result}: %{repository_slug}@%{branch}, build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>)"
  email: false
