---
# tasks file for gnome

- name: install software
  ansible.builtin.package:
    name: "{{ gnome_packages }}"
    state: present
    exclude: "{{ gnome_exclude | default(omit) }}"
    allowerasing: "{{ gnome_allowerasing | default(omit) }}"
