---
# tasks file for gnome

- name: install software on redhat like systems
  ansible.builtin.package:
    name: "{{ gnome_packages }}"
    state: present
    exclude: "{{ gnome_exclude | default(omit) }}"
    skip_broken: yes
    allowerasing: yes
  when:
    - ansible_os_family == "RedHat"

- name: install software on non-redhat like systems
  ansible.builtin.package:
    name: "{{ gnome_packages }}"
    state: present
  when:
    - ansible_os_family != "RedHat"
