---
# tasks file for gnome

- name: install software using ansible 2.10 and newer
  ansible.builtin.package:
    name: "{{ gnome_packages }}"
    state: present
    exclude: "{{ gnome_exclude | default(omit) }}"
    allowerasing: yes
