---
# tasks file for gnome

- name: configure gnome
  block:
    - name: install software
      package:
        name: "{{ gnome_packages }}"
        state: present
        allowerasing: yes

    - name: install software with excluded
      package:
        name: "{{ gnome_packages }}"
        state: present
        exclude: "{{ gnome_exclude | default(omit) }}"
        skip_broken: yes
        allowerasing: yes
  when:
    - ansible_distribution in [ "RedHat", "CentOS", "Fedora" ]
